name: Upstream Sync

on:
  schedule:
    - cron: "0 */6 * * *" # run every 6 hours
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure git auth
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git remote add upstream https://github.com/LunaTechLab/MoonTV.git || git remote set-url upstream https://github.com/LunaTechLab/MoonTV.git

      - name: Sync from upstream excluding workflows
        run: |
          set -e
          git fetch upstream main --tags --prune --depth=0
          git merge --no-ff --no-commit upstream/main || true
          git restore --worktree --staged .github/workflows || true
          if ! git diff --quiet --staged; then
            git commit -m "Sync upstream (exclude .github/workflows)"
            git push origin HEAD:main
          else
            echo "No changes to push (only workflows changed or nothing changed)."
          fi

  # 下面的 Sync check / Delete workflow runs 保持不变

      - name: Sync check
        if: failure()
        run: |
          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
          exit 1

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
